template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "udm"
__UND2C_TRG__ = "kv"
__UNDEFINED_SOURCE__ = "Udmurt"
__UNDEFINED_TARGET__ = "Komi Zyryan"
__UND_SRC__ = "udm"
__UND_TRG__ = "kpv"
